server:
  port: 7070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java13AuthDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secretKey: ${java13secretkey}
  audience: ${java13audience}
  issuer: ${java13issuer}